### ISSUE TITLE
Icons load incorrectly (very large) in server side when using library.add (Nuxt.js)

### ISSUE THREAD

**Issue by yliaho** [FortAwesome/vue-fontawesome#14]
![](https://i.imgur.com/dlDOd9e.gif)  
  
Icons render initially very large until finally settling down to wanted size. I'm using [nuxt](https://github.com/nuxt/nuxtjs.org) with server side rendering.

Fontawesome gets loaded as a plugin with nuxt.js:
```javascript
import fontawesome from '@fortawesome/fontawesome'
import iconCSS from './icon-css.css'
import {
  faFrown
} from '@fortawesome/fontawesome-free-solid'

fontawesome.dom.styles(iconCSS)

fontawesome.library.add(
  faFrown
)

export default fontawesome
```    
  
Am I missing something here? Is there a workaround for this behavior?

**Comment by robmadole** [comment]
@yliaho the issue here is probably two-fold.

First the call to `fontawesome.dom.styles()` returns a string that represents the CSS that is necessary to properly display icons. It looks like you are trying to pass it something which will not work as expected.

Second, the reason that the icon appears large to begin with is that it's being displayed before the CSS is parsed and re-paints. If you are doing server-side rendering and you rely on the CSS to size the icon you'll need to make sure that the CSS for Font Awesome is available first. You could do this by in-lining the CSS into the page or by writing/adding to the Nuxt plugin so that it's inserted.

Under the hood the JS library is trying to add the CSS for you and this is what causes the flash (I'm guessing). Try setting this config option as part of your plugin to remove this option and see if that leaves the icon large:

```javascript
fontawesome.config = {
  autoAddCss: false
}
```

That disables the automatic inserting of a `<style>` tag into the `<head>` of your doc.

**Comment by yliaho** [comment]
@robmadole sorry for the late reply - yeah, that did the trick! Thank you!

**Comment by chewtoys** [comment]
@yliaho could you share the plugin?

**Comment by OriginalEXE** [comment]
@chewtoys Here is my example (using the pro version):

`font-awesome.js (place in the plugins folder):`
```
import fontawesome from '@fortawesome/fontawesome';
import { faCoffee, faCode } from '@fortawesome/fontawesome-pro-regular';

fontawesome.config = {
  autoAddCss: false,
};

fontawesome.library.add(faCoffee, faCode);
```

`nuxt.config.js (relevant part)`
```
css: [
    'normalize.css',
    '@fortawesome/fontawesome/styles.css',
    '@/assets/css/main.scss',
  ],
```

`index.vue`
```
<template>
  <div>
    <p>Hello! <font-awesome-icon :icon="['far', 'code']"></font-awesome-icon><p>
  </div>
</template>

<script>
import FontAwesomeIcon from '@fortawesome/vue-fontawesome';

export default {
  components: {
    FontAwesomeIcon,
  },
};
</script>
```

**Comment by codeofsumit** [comment]
`@fortawesome/fontawesome-pro-regular` where in the documentation are you finding this? I have no idea what packages to install to get started with pro 🤔

**Comment by robmadole** [comment]
@codeofsumit here ya go https://fontawesome.com/how-to-use/use-with-node-js#pro

**Comment by r31gnf1r3** [comment]
Tested with caching, issues persists. Have to fixup how SVG is rendered with CSS.

**Comment by samuelterra22** [comment]
I had the same problem using Nuxtjs but I fixed just [reading the readme](https://github.com/FortAwesome/vue-fontawesome#nuxtjs)

![image](https://user-images.githubusercontent.com/11915449/48412912-2976db80-e72d-11e8-8dee-4e616092bbe6.png)

**Comment by Elchin555** [comment]
<img width="239" alt="Screenshot 2023-03-10 at 01 27 59" src="https://user-images.githubusercontent.com/67804326/224164304-95bd31d9-fb39-423a-a8b0-06020a756ad9.png">
add extractCSS:true, nuxt.config.js  to build{ }
