### ISSUE TITLE
Self-closing tags

### ISSUE THREAD

**Issue by mark-meyer** [FortAwesome/vue-fontawesome#147]
The documentation here warns to avoid self-closing tags:

https://github.com/FortAwesome/vue-fontawesome#quick-warning-about-self-closing-tags

The documentation here uses self-closing tags:

https://fontawesome.com/how-to-use/on-the-web/using-with/vuejs

**Comment by robmadole** [comment]
@mark-meyer it's less typical to be in a situation where self-closing tags are going to cause you issues. If you're building a modern app (with vue-cli, webpack, etc) self-closing tags aren't an issue because you are running these through `vue-loader` typically. And self-closing are even preferred with most eslint configurations.

Do we need to make the documentation clearer?
