### ISSUE TITLE
How to use font-awesome-icon as a background image?

### ISSUE THREAD

**Issue by mrichman** [FortAwesome/vue-fontawesome#229]
Is there any way to use this component as a background image or watermark for a div?

**Comment by HonzaMikula** [comment]
Related question. I very often use in my current Nuxt project something like
```
&::before
      +fa-icon()

      @extend .fab
      content: fa-content($fa-var-linkedin)
```

How would I do it using this library? Is it even possible?

**Comment by robmadole** [comment]
This component does not support background images or pseudo elements.

@mrichman I would recommend that you use the raw SVG files which are available from our [download page](https://fontawesome.com/download) or from the `@fortawesome/fontawesome-free` and `@fortawesome/fontawesome-pro` packages inside the `svg` directory. If you have a CSS pre-processor you should be able to inline those icons as [data URIs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs).

@HonzaMikula you should probably consider using Webfonts and CSS instead of the `vue-fontawesome` package if pseudo-elements is important to you. We have some [documentation here](https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements).
