### ISSUE TITLE
How would I use this with the pro license?

### ISSUE THREAD

**Issue by wahidrahim** [FortAwesome/vue-fontawesome#31]
I am wondering how I would access the pro icons, if I am using this package?

Thanks.

**Comment by OriginalEXE** [comment]
Hi,

In your project directory, create a file called `.npmrc` and add this to it:
`@fortawesome:registry=https://npm.fontawesome.com/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX`, replacing the X'es with whatever you find while logged in to your account [here](https://fontawesome.com/account#account-packages).

Then simply `npm install @fortawesome/fontawesome-pro-regular` or whatever the package you need and enjoy :)

**Comment by robmadole** [comment]
Thanks @OriginalEXE . Hollar if you have any issues @wahidrahim

**Comment by codeofsumit** [comment]
Thanks @OriginalEXE  - Should be in the Get Started docs somewhere 👍  - still not sure what packages to install though. I just want all of Pro used with vue-fontawesome

**Comment by ThomasKientz** [comment]
I was mixing up my licence with the token.

Find your proper npm token here : [](https://fontawesome.com/account/services)

**Comment by gregveres** [comment]
This has changed. So the solution that @OriginalEXE mentioned a couple of years ago is no longer the way to do it. Instead of putting the solution here, I will link to the official docs. I would highly recommend that you log in to your account because the docs page will be modified to show you the exact content of the .npmrc file with your license key. 

So log in, then go to [this page](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers) and follow the instructions. It worked like a charm for me.
