### ISSUE TITLE
Cloudflare Pages Deployment Fails with 401 Unauthorized

### ISSUE THREAD

**Issue by pingustar** [FortAwesome/vue-fontawesome#312]
**Describe the bug**

Auto - Deployment (CD) with Cloudflare Pages fails after installing FontAwesome packages. Installation works fine on localhost.

*Error Msg:*
`
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/free-solid-svg-icons/-/5.15.3/free-solid-svg-icons-5.15.3.tgz: Request failed \"401 Unauthorized\"".
`

**Comment by jasonlundien** [comment]
Hi @pingustar -- 

I see this is an older issue... are you still having problems ?

We have had a few releases since this issue, including our "Official" Vue 3 release and some updates to our Vue 2 package.  I am going to close this issues as I have not heard or seen this issue since this post.  If you feel we need to open this again, just let us know!
