### ISSUE TITLE
icon weight prefix not working in Vuejs

### ISSUE THREAD

**Issue by glutjenkossink** [FortAwesome/vue-fontawesome#363]
**Describe the bug**
When trying to import a font other then solid it will give you a prefix error.
`Could not find one or more icon(s) 
Object { prefix: "fas", iconName: "rocket" }
 `

**To Reproduce**
Create a Vue 3 project (mine is with Vite) and add font-awesome and the pro fonts etc.
Try importing an icon from the library other then pro-solid.
Try displaying the font and it will give the error above.
For example:

main.ts
<img width="458" alt="image" src="https://user-images.githubusercontent.com/93208883/153163125-26464346-eeb3-4278-bd9e-02db46881f9f.png">

app.vue
<img width="921" alt="image" src="https://user-images.githubusercontent.com/93208883/153163082-de1a19e1-de62-4263-99a0-2eb555569f5e.png">

The first 'bicycle' icon will work because its from the solid library.

<img width="906" alt="image" src="https://user-images.githubusercontent.com/93208883/153163213-523e3307-3673-4be1-84a5-f69f479d6f4f.png">
Will not work and give you the prefix error.

`<font-awesome-icon :icon="['fa-light', 'rocket']" size="3x" />`
Is the only way to get fonts other then solid to work.

**Expected behavior**
When not using the same icon in different weights you should be able to just add them normally and not as an array.
At the very least the code you get from the website should be working.

**Screenshots**
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/93208883/153162684-0362327e-a86a-40dc-8dff-738744dd86d0.png">

**Version and implementation**
Version:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/93208883/153163437-0450507e-bcb6-4b90-9c39-00afb057e7e6.png">

Browser and version:
Chrome: 98.0.4758.80
Firefox Developer: 98.0b1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

@robmadole is it possible that the [official VUE component](https://github.com/FortAwesome/vue-fontawesome) needs to be updated?

**Comment by robmadole** [comment]
We haven't updated the pre-release yet to support the new syntax for Vue 3. This is on the todo list but hasn't been completed.

**Comment by christhofer** [comment]
This is incorrect
`<font-awesome-icon :icon="['fa-light', 'rocket']" size="3x" />`

It should be 
`<font-awesome-icon :icon="['fal', 'rocket']" size="3x" />`

**Comment by glutjenkossink** [comment]
@christofer In the time when I was writing it that 'fal' was not working but 'fa-light' was. Could be that an update changed this. I wouldn't know what the syntax is because I'm simply not using FontAwesome in my projects currently as this is just poor implementation.

I find it kinda odd that the new FA6 is released nearly 4 months ago already and this issue still isn't fixed.
Its especially odd if you think about that this impacts the actual paying users the most and the documentation is still not updated either.

**Comment by jasonlundien** [comment]
Hey @glutjenkossink ---

We have updated our [Vue 2 and Vue 3 docs](https://fontawesome.com/v6/docs/web/use-with/vue/add-icons) on the proper usage of our icons.

In the case of the `fa-rocket` icon (and for the `fa-bicycle` icon as well) you can choose to do the following:
- string syntax: `<font-awesome-icon icon="fa-light fa-rocket" />`
- array syntax:  `<font-awesome-icon :icon="['fal', 'rocket']" />`

As far as the `fa-bicycle` working without a style -- this is because we have defaulted "solid" for users that do NOT select a style.  You can always change the [default style](https://fontawesome.com/v6/docs/web/dig-deeper/style-switching?#fast-style-switching-with-svg-js) if you prefer.

I have tested the string and array syntax with Vue 3 using typescript and all seems to be working well so I am going to go go ahead and close this issue.  If you feel it should be re-opened just let us know.
