### ISSUE TITLE
Documentation is completely gone

### ISSUE THREAD

**Issue by xaddict** [FortAwesome/vue-fontawesome#383]
**Describe the bug**
This repo points to https://fontawesome.com/docs/web/use-with/vue/ for documentation on how to use the component, but that page points to https://fontawesome.com/v5/docs/web/use-with/vuejs and THAT page in turn points to either this repository or https://fontawesome.com/docs/web/use-with/vue/ (which doesn't have any documentation on the power transforms or Vue component props). So it seems all the documentation is gone now.

There used to be a dedicated page where vue-fontawesome was explained.

**Expected behavior**
A markdown file or other way to read the documentation on how features of Font Awesome are usable in vue-fontawesome

**Comment by jasonlundien** [comment]
Hey there @xaddict --

You are correct, the repo points to:  https://fontawesome.com/docs/web/use-with/vue/

But where are you seeing we are redirecting to v5 docs? 

> but that page points to https://fontawesome.com/v5/docs/web/use-with/vuejs

**Comment by kylepulver** [comment]
not the original poster, but i actually made my way here because of the issue of seemingly no documentation on the component.

the docs here: https://fontawesome.com/docs/web/use-with/vue/ show the setup, but that's all. i just noticed that all the way down the left side on the sidebar there are the following links:
- Set Up with Vue
- Add Icons with Vue
- Adding Icon Styling with Vue
- Dig Deeper
- Use Vue With...
- Troubleshoot

None of these links work, as they direct to headers that do not exist on the installation page. Instead the headers are:
- Add SVG Core
- Add Icon Packages
- Add the Vue Component
- You're Ready to Add Icons!

I might have missed something incredibly obvious but the only way I could find out what props were available for the component was to look at the source directly

**Comment by xaddict** [comment]
I eventually found the full documentation for the vue component (like the props). I can’t remember how I got there but I think it got something to do with screen width which hid a side menu 🤷🏼‍♂️

Met vriendelijke groet,
Luuk Lamers

**Comment by jasonlundien** [comment]
This is interesting for sure.  I see what you are saying by clicking the link provided (https://fontawesome.com/docs/web/use-with/vue/).  If you click on the side link(s) it seems to always take you to the setup page for Vue.

Yet this is the same url as when you "manually" visit www.fontawesome.com, click on Docs, Web, Setup with Vue.  All the links in the side menu seem to be working fine doing it this way... yet the links do NOT work when you click the link we provided... weird.  Hmmm, ok.  Thank you for pointing this out, I will get this fixed up !!!

**Comment by jasonlundien** [comment]
Ok, we have a temporary fix going in.  Bottom line, there is a bug, we believe, with our fontawesome vue-press docs and how it is rendering the pages for our vue, and only vue, docs it appears.  We are getting a console error of `Cannot read properties of undefined (reading '_transitionClasses')` in our production environment, as you all have seen.  Yet our dev environment is not seeing the same result so we need to spend some time on reproducing this in our local dev.

I am going to keep this open so we can spend a little more time on this one.  Thanks for bringing this to our attention, greatly appreciated!

**Comment by jasonlundien** [comment]
Fix on PR: [Update docs for new links](https://github.com/FortAwesome/vue-fontawesome/pull/497#top)
#497

**Comment by jasonlundien** [comment]
I believe we have this fixed up now with the Release of 3.0.8; docs are working as expected now.

Let us know if you see anything else and thank you !!!
