### ISSUE TITLE
Add example of using Pro version

### ISSUE THREAD

**Issue by yordis** [FortAwesome/vue-fontawesome#87]
Hey folks, I am confused how to do this. Could you add some example on the Readme please?

**Comment by robmadole** [comment]
Hey there,

We currently have some pre-release candidates out (we are calling them 5.1.0) that address some of the documentation issues.

We are doing the work (and documentation) on the `development` branch:

https://github.com/FortAwesome/vue-fontawesome/tree/development

Would you be willing to give this a try? Check out the UPGRADING.md for detailed instructions.

Also remember that since this is a pre-release you need to use NPM tag `@prerelease` like:

```
$ npm i --save @fortawesome/fontawesome-svg-core@prerelease
```

Please let us know how the upgrade goes and if you run into any problems. We are working hard to get the 5.1.0 release stabilized.

**Comment by XanderLuciano** [comment]
Install main modules:
`npm i @fortawesome/vue-fontawesome @fortawesome/fontawesome-svg-core`

Add pro svg icons:  
`npm i @fortawesome/pro-regular-svg-icons`
`npm i @fortawesome/pro-solid-svg-icons`
`npm i @fortawesome/pro-light-svg-icons`

Add brand icons:  
`npm i @fortawesome/free-brands-svg-icons`

Basic Usage:  
```javascript
import Vue from 'vue'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { library } from '@fortawesome/fontawesome-svg-core'
import { far } from '@fortawesome/pro-regular-svg-icons'
import { fas } from '@fortawesome/pro-solid-svg-icons'
import { fal } from '@fortawesome/pro-light-svg-icons'
import { fab } from '@fortawesome/free-brands-svg-icons'

library.add(far);
library.add(fas);
library.add(fal);
library.add(fab);

Vue.component(FontAwesomeIcon.name, FontAwesomeIcon);
```

This doesn't do tree shaking though, so you'll be importing a huge amount of icons, but the current documentation covers tree shaking already.

You may need to add the css stylesheet also (if you are using SSR for example):

```sass
import "@fortawesome/fontawesome-svg-core/styles.css"
```

You could add this to webpack, or import to a vue template, or use the hosted version in the head:
```html
<head>
    <link href="https://use.fontawesome.com/releases/v5.1.0/css/svg-with-js.css" rel="stylesheet"></link>
</head>
```

**Comment by XanderLuciano** [comment]
@tiagomatosweb You are using the wrong names, instead of `faCoffee` it's `farCoffee` for the regular, and `falCoffee` for the light version.

**Comment by tiagomatosweb** [comment]
hahahaaha of course! Dammm...

**Comment by zzAutumn** [comment]
here is my solution.
this is a Vue project.
in icon.js
`
import Vue from 'vue';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faCoffee } from '@fortawesome/free-solid-svg-icons';
import { faUser } from '@fortawesome/free-regular-svg-icons';

Vue.component('font-awesome-icon', FontAwesomeIcon);

library.add(faCoffee);
library.add(faUser);
`

in main.js
`
import './plugins/icon';
`

in .vue I use icon in this way
`
<font-awesome-icon :icon="['far', 'user']" />
`

and it works.

**Comment by EvanAgee** [comment]
To clarify for those using the PRO versions of Font Awesome you'll need to pass an array into your `<font-awesome-icon :icon="['fal', 'times']" />` per https://github.com/FortAwesome/vue-fontawesome/tree/development#shorthand-that-assumes-a-prefix-of-fas

**Comment by jasonlundien** [comment]
Hi @yordis 

We have released several version of our Vue component including our official Vue 3 component, since you first posted this issue, which allows you to add and use Pro icons from FA5 or FA6 in a string or array [format](https://fontawesome.com/docs/web/use-with/vue/add-icons#call-the-icons).

Saying that, I am going to go ahead and close this issue at this time.  If you feel this is in error and this issue should remain open just let us know and we can open back up if necessary.
